/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowRouteImport } from './routes/how'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ClientRouteRouteImport } from './routes/_client/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientSettingsRouteImport } from './routes/_client/settings'
import { Route as ClientReportRouteImport } from './routes/_client/report'
import { Route as ClientProjectsRouteImport } from './routes/_client/projects'
import { Route as ClientProfileRouteImport } from './routes/_client/profile'
import { Route as ClientPlanRouteImport } from './routes/_client/plan'
import { Route as ClientMessageRouteImport } from './routes/_client/message'
import { Route as ClientDashboardRouteImport } from './routes/_client/dashboard'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminTemplatesRouteImport } from './routes/_admin/admin/templates'
import { Route as AdminAdminSupportRouteImport } from './routes/_admin/admin/support'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin/reports'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin/admin/payments'
import { Route as AdminAdminBlogsRouteImport } from './routes/_admin/admin/blogs'
import { Route as AdminAdminProjectsIndexRouteImport } from './routes/_admin/admin/projects/index'
import { Route as AdminAdminProjectsIdRouteImport } from './routes/_admin/admin/projects/$id'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientReportRoute = ClientReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientPlanRoute = ClientPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientMessageRoute = ClientMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminTemplatesRoute = AdminAdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSupportRoute = AdminAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBlogsRoute = AdminAdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminProjectsIndexRoute = AdminAdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminProjectsIdRoute = AdminAdminProjectsIdRouteImport.update({
  id: '/admin/projects/$id',
  path: '/admin/projects/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/dashboard': typeof ClientDashboardRoute
  '/message': typeof ClientMessageRoute
  '/plan': typeof ClientPlanRoute
  '/profile': typeof ClientProfileRoute
  '/projects': typeof ClientProjectsRoute
  '/report': typeof ClientReportRoute
  '/settings': typeof ClientSettingsRoute
  '/admin/blogs': typeof AdminAdminBlogsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/projects/$id': typeof AdminAdminProjectsIdRoute
  '/admin/projects/': typeof AdminAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/dashboard': typeof ClientDashboardRoute
  '/message': typeof ClientMessageRoute
  '/plan': typeof ClientPlanRoute
  '/profile': typeof ClientProfileRoute
  '/projects': typeof ClientProjectsRoute
  '/report': typeof ClientReportRoute
  '/settings': typeof ClientSettingsRoute
  '/admin/blogs': typeof AdminAdminBlogsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/projects/$id': typeof AdminAdminProjectsIdRoute
  '/admin/projects': typeof AdminAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_client': typeof ClientRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/signup': typeof SignupRoute
  '/why': typeof WhyRoute
  '/_client/dashboard': typeof ClientDashboardRoute
  '/_client/message': typeof ClientMessageRoute
  '/_client/plan': typeof ClientPlanRoute
  '/_client/profile': typeof ClientProfileRoute
  '/_client/projects': typeof ClientProjectsRoute
  '/_client/report': typeof ClientReportRoute
  '/_client/settings': typeof ClientSettingsRoute
  '/_admin/admin/blogs': typeof AdminAdminBlogsRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/support': typeof AdminAdminSupportRoute
  '/_admin/admin/templates': typeof AdminAdminTemplatesRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/projects/$id': typeof AdminAdminProjectsIdRoute
  '/_admin/admin/projects/': typeof AdminAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/how'
    | '/login'
    | '/plans'
    | '/signup'
    | '/why'
    | '/dashboard'
    | '/message'
    | '/plan'
    | '/profile'
    | '/projects'
    | '/report'
    | '/settings'
    | '/admin/blogs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/how'
    | '/login'
    | '/plans'
    | '/signup'
    | '/why'
    | '/dashboard'
    | '/message'
    | '/plan'
    | '/profile'
    | '/projects'
    | '/report'
    | '/settings'
    | '/admin/blogs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_client'
    | '/assessment'
    | '/how'
    | '/login'
    | '/plans'
    | '/signup'
    | '/why'
    | '/_client/dashboard'
    | '/_client/message'
    | '/_client/plan'
    | '/_client/profile'
    | '/_client/projects'
    | '/_client/report'
    | '/_client/settings'
    | '/_admin/admin/blogs'
    | '/_admin/admin/payments'
    | '/_admin/admin/reports'
    | '/_admin/admin/settings'
    | '/_admin/admin/support'
    | '/_admin/admin/templates'
    | '/_admin/admin/users'
    | '/_admin/admin/'
    | '/_admin/admin/projects/$id'
    | '/_admin/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  HowRoute: typeof HowRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  SignupRoute: typeof SignupRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client/settings': {
      id: '/_client/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/report': {
      id: '/_client/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ClientReportRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/projects': {
      id: '/_client/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/profile': {
      id: '/_client/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/plan': {
      id: '/_client/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof ClientPlanRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/message': {
      id: '/_client/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof ClientMessageRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_client/dashboard': {
      id: '/_client/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/templates': {
      id: '/_admin/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminAdminTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/support': {
      id: '/_admin/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/blogs': {
      id: '/_admin/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminAdminBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/projects/': {
      id: '/_admin/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminAdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/projects/$id': {
      id: '/_admin/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminAdminProjectsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminBlogsRoute: typeof AdminAdminBlogsRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSupportRoute: typeof AdminAdminSupportRoute
  AdminAdminTemplatesRoute: typeof AdminAdminTemplatesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminProjectsIdRoute: typeof AdminAdminProjectsIdRoute
  AdminAdminProjectsIndexRoute: typeof AdminAdminProjectsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminBlogsRoute: AdminAdminBlogsRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSupportRoute: AdminAdminSupportRoute,
  AdminAdminTemplatesRoute: AdminAdminTemplatesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminProjectsIdRoute: AdminAdminProjectsIdRoute,
  AdminAdminProjectsIndexRoute: AdminAdminProjectsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClientRouteRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientMessageRoute: typeof ClientMessageRoute
  ClientPlanRoute: typeof ClientPlanRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientProjectsRoute: typeof ClientProjectsRoute
  ClientReportRoute: typeof ClientReportRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientMessageRoute: ClientMessageRoute,
  ClientPlanRoute: ClientPlanRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientProjectsRoute: ClientProjectsRoute,
  ClientReportRoute: ClientReportRoute,
  ClientSettingsRoute: ClientSettingsRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  HowRoute: HowRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  SignupRoute: SignupRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
